sudo: false
language: node_js
node_js:
- '8'
services:
  - docker
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- docker-compose up -d
 
install:
- npm install
script:
- npm run build
- npm test

deploy:
  provider: npm
  email: "EMAIL_ADDRESS"
  api_key: "NPM_TOKEN"
  on:
    branch: production
  skip_cleanup: true
  tag: next